vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        recipe_thumbnail:
            uri_prefix: /images/recipes_thumbnails
            upload_destination: '%kernel.project_dir%/public/images/recipes_thumbnails'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
